# Generated by Django 5.2.8 on 2025-12-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Full course title, e.g., 'AI Data Science and Analytics with GenAI'.", max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from title).', max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Short/summary description displayed in course listings.')),
                ('full_description', models.TextField(blank=True, help_text='Detailed description from course detail pages (optional).')),
                ('price_original', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount.', max_digits=10, null=True)),
                ('price_discounted', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price currently shown on the site.', max_digits=10, null=True)),
                ('currency', models.CharField(default='₹', help_text='Currency symbol or code (default: INR).', max_length=10)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount % applied (if available).', null=True)),
                ('language', models.CharField(blank=True, help_text='Primary language of instruction (if specified).', max_length=100)),
                ('schedule', models.CharField(blank=True, help_text="Schedule/batch info (e.g., 'Live Batch Hinglish').", max_length=255)),
                ('course_validity', models.CharField(blank=True, help_text="Validity period of the course access (e.g., '1 year').", max_length=255)),
                ('is_live', models.BooleanField(default=False, help_text='Whether the course has live sessions.')),
                ('image', models.ImageField(blank=True, help_text='Course thumbnail/image (optional).', null=True, upload_to='course_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorizing courses (e.g., DSA, Web Development).', related_name='courses', to='shreyans.coursetag')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['title'],
            },
        ),
    ]
