# Generated by Django 5.2.8 on 2026-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreyans', '0004_alter_cart_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
